FROM  jenkins/jnlp-slave
COPY  empty-test-file   /jenkins-slave5
USER  root
COPY  plugins.txt  /usr/local/bin/
COPY  sources.list /usr/local/bin/
#RUN  /usr/local/bin/install-plugins.sh ansicolor
#RUN  /usr/local/bin/install-plugins.sh greenballs
#RUN  /usr/local/bin/install-plugins.sh kubernetes
ENV  MAVEN_HOME=/usr/local/maven/apache-maven-3.6.3
ENV  PATH=${MAVEN_HOME}/bin:${PATH}
ENV  NODE_HOME=/usr/local/node
ENV  PATH=$NODE_HOME/bin:$PATH
RUN  cd /usr/local/bin/ && \
     ./install-plugins.sh < plugins.txt || true   && \
     cd /opt &&\
     wget https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz && \
     mkdir -pv /usr/local/maven/  && \
     tar xzvf  apache-maven-3.6.3-bin.tar.gz  -C /usr/local/maven/  && \
     apt  update && \
     apt  install gcc   -y  &&\
     apt install  pbzip2   -y  && \
     apt  install sshpass -y  && \
     apt install  vim  zip  -y  && \
     wget  https://npm.taobao.org/mirrors/node/latest-v13.x/node-v13.9.0-linux-x64.tar.gz  && \
     tar  xzvf  node-v13.9.0-linux-x64.tar.gz  -C /usr/local/  && \
     cd /usr/local/  && \
     mv node-v13.9.0-linux-x64/ node  && \
     export   NODE_HOME=/usr/local/node  && \
      export   PATH=$NODE_HOME/bin:$PATH  && \
     /usr/local/node/bin/npm install -g cnpm --registry=https://registry.npm.taobao.org  && \
     /usr/local/node/bin/npm config set registry https://registry.npm.taobao.org  && \
     /usr/local/node/bin/npm  update  && \
     cnpm update  && \
     cd /opt && \
     rm -rfv /opt/* && apt-get clean && rm -rf /var/lib/apt/lists/*
